### ISSUE TITLE
Adjustments for angular2 rc.1

### ISSUE THREAD

**Issue by sgbeal** [vladvelici/ng2-mock-server#1]
Hi!

we were unable to get ng2-mock-server running as a node module (and unable to figure out why, because none of us know much of anything about node), but we have since integrated it directly, as-is into our source tree and it's working great. We have replaced json-server with your mock because it's far simpler for our development workflow (no need for a second server process).

i'm trying to upgrade us from angular2 beta-12 (14?) to rc.1 and had to make the following changes to your code (unfortunately i have no diff, but the changes were minimal):
- all of the modules were renamed: 'angular2/xxx' ==> '@angular/xxx'. A couple require more notable changes, but i don't recall what they are off-hand :/.
- the http module has to be loaded separately in package.json:
  
  "@angular/http": "2.0.0-rc.1",
- most notably, i had to change this import from mocksrv.service.ts:
  
  import {Connection, ConnectionBackend} from '@angular/http/src/interfaces';

(http/src/interfaces uses to be in the main a2 module)

After that, broccoli compiles it :). i still haven't gotten our tree to the point where i can actually try that out, but it at least compiles.

Thanks for the code!

**Comment by vladvelici** [comment]
Hi,

Glad to hear you're using this. Thank you for the comments and snippets!

I will look into why the node module doesn't work, but it's likely because the angular2 package is now `@angular/<module>`, and not `angular2` like before.

Can't promise anything as I've got quite a lot to do these days but will do my best to push a release for the latest version of Angular.

If you have time and would like to make that happen more than happy to accept a pull request.

Enjoy your Sunday!

**Comment by sgbeal** [comment]
The node module problem was almost certainly an error or misunderstanding on our part (and with angular2 beta 12, which still used <angular2> for module names). None of us know how to properly use npm/node/etc and we're just kind of stumbling along with a too-short project deadline, so we didn't bother looking into it. i tried dropping it as-is into our tree and that worked great, so we never bothered exploring a proper fix. Just today i got the tree working with the a2 RC1, and part of that involved patching your files for the new naming conventions. (BTW, it still works after those changes - i was able to verify that a couple hours after posting the ticket.)

**Comment by sgbeal** [comment]
i have bundled up our changes - if you like, i can send them via email (just let me know which address).

Oh, wait - github will let me attach it here. Here you go...

[ng2-mock-server-a2rc1.zip](https://github.com/vladvelici/ng2-mock-server/files/254413/ng2-mock-server-a2rc1.zip)

**Comment by vladvelici** [comment]
Thanks a lot! I'll have a look soon and make a release.

**Comment by sgbeal** [comment]
This might be helpful for you: here's how we set up your mocker depending on whether we're building in dev or prod mode (using angular-cli's "environment.ts" support):

```
    import {environment} from "./environment" /* gets created by angular-cli build process, so intelliJ cannot resolve it.
                                                 See <top-src-dir>/config/environment.{prod,dev}.ts. */;
    // ... all the normal bits, then ...       
    let providers:any[] = [
        ... all normal providers (not mocks) ...
    ];
    environment.addEnvironmentProviders(providers) /* dev impl plugs in REST mocker */;
    bootstrap(OurMainComponent, providers).then((componentRef:ComponentRef<any>)=>{
        environment.doEnvironmentSetup(componentRef.injector) /* dev impl initializes REST mocker */;
    });
```

Our `config/environment.prod.ts`:

```
    export const environment = {
        production: true,
        // No-op in prod build.
        addEnvironmentProviders: function (providers:any[]/*ignored*/){},
        // No-op in prod build.
        doEnvironmentSetup: function(injector:any/*ignored*/){}
    };
```

Our `config/environment.dev.ts`:

```
    /* this file is manipulated by the build process, and imports cannot be properly resolved from intellij. That's okay - not an error.
       For import purposes, the final generated copy of this file will live in the 'app' directory. */

    import {Injector} from '@angular/core';
    //noinspection TypeScriptCheckImport
    import {setupNmsMockRouter} from './services/rest/setupNmsMockRouter' ;
    //noinspection TypeScriptCheckImport
    import {MOCK_SERVER_PROVIDERS, MockSrvRouter} from './services/rest/mocker/http';

    const pleaseInjectNmsMockRouter = 1 || window.location.href.indexOf('mock=1')>0 /* temporary internal mock activation flag */;

    export const environment = {
      production: false,

      /*
        Called via main.ts and passed the array of Providers which will eventually be passed to bootstrap(), so
        this routine may append any it needs to that list.
      */
      addEnvironmentProviders: function (providerList:any[]){
        if(pleaseInjectNmsMockRouter) {
          console.log("Injecting MOCK_SERVER_PROVIDERS...");
          providerList.push(MOCK_SERVER_PROVIDERS);
        }
      },

      /*
        performs the setup of the client-side mock server. Must be passed the injector property of
        the object obtained like this:


        bootstrap(...).then( aComponentRef => {
           environment.doEnvironmentSetup(aComponentRef.injector);
        });
      */
      doEnvironmentSetup: function(injector:Injector){
        if(!pleaseInjectNmsMockRouter) {
          console.warn("NOT injecting REST mocking bits. Pass mock=1 when (re)loading the page to enable them.");
          return;
        }
        let router = <MockSrvRouter> injector.get(MockSrvRouter);
        console.warn("Injecting REST mocking bits...");
        setupNmsMockRouter(router);
      }
    };
```
