### ISSUE TITLE
onComplete handler not triggered

### ISSUE THREAD

**Issue by sgbeal** [vladvelici/ng2-mock-server#3]
i'm not 100% sure this is a bug in this code, but it seems to be. Consider a call chain like:

```
  let log = console.log.bind(console);
  let error = console.error.bind(console);
  let warn = console.warn.bind(console);
  this.httpService.get(...).subscribe(log, error, warn)
```

when using this mock, the 3rd (onComplete) callback is not consistently called (only rarely, and i am not certain under which conditions). When not using the mock, it is triggered consistently after the first callback (but apparent;y not if the onError callback is called).

**Comment by vladvelici** [comment]
Thanks for the issue, it was a bug. Fixed now.

I can't figure out when it was called, and why, as there was nothing in the code calling `.complete()`.

Changes in npm now (version 0.0.3).
